### ISSUE TITLE
Enviroment details

### ISSUE THREAD

**Issue by crised** [jermwatt/RNN_demo#12]
There is no suggestion on suggested Keras version and others packages for this project.

I went on EC2, used Udacity dl AMI, then updated all pip packages using http://stackoverflow.com/a/3452888, this gives you Keras 2.0.x

**Comment by cnimativ** [comment]
im using keras 2.0.2 and tensorflow-gpu 1.0.0. works, but still waiting for big data set to finish training, hopefully chrome wont mess w/ the progress
